Apple Clone
haraphat01/apple-clone pull request #1
Opened 2020-04-13 22:41 UTC by haraphat01

This is the clone of Apple's Website Page. This page is built with just Html and CSS. Some amazing it has is:

- Usage of Grid and Flex

- Usage of Gradient Background and also,

- Usage of the background picture.

2020-04-13 23:31 UTC, uryelah commented
Hello **Arafat Akata**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**Good job with the previous fixes, you did well working with backgrounds 🌟**

There are still some required checks you need to fulfill in order to continue to the next project, so hang in there! 💪

---------     

## Required Changes 🏗 👷‍♀ 

- [ ] All but the last navbar element should be links. Make sure the apple logo is also a link.

- [ ] Make sure there are no unnecessary borders around your page elements.
- [ ] The main image should take 100% of the screen width regardless of its size.

Compare your clone and the original site in the screenshots below:
**Clone:**
![Screenshot_2020-04-13 Apple Clone](https://user-images.githubusercontent.com/16193212/79170414-ad6f4000-7dc5-11ea-91a0-089a10ff14ef.png)

**Original site:**
![Screenshot_2020-04-13 Apple(1)](https://user-images.githubusercontent.com/16193212/79170412-ac3e1300-7dc5-11ea-85ba-77bf69e29279.jpg)

-----

- [ ] The elements at the bottom of the main image should be links, notice how the link you to other pages in the[ original website](https://web.archive.org/web/20140301004610/http://www.apple.com/) Check the requirement below and make sure to fulfill it. 
![Screenshot_2020-04-13 dist html_css building_with_backgrounds_and_gradients md · master · Microverse guides tse code_review](https://user-images.githubusercontent.com/16193212/79123242-17f59100-7d70-11ea-8b8d-e8cd46ba790d.png)

----

- [ ] [OPTIONAL] Be more semantic! Use the `main` tag for the first section and `aside` for the second one with the bottom images.

If the page looks correct on your monitor you can use your [browser responsive tools](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode) to make sure the page still looks correct on slightly wider monitors.

------

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-04-14 06:16 UTC, haraphat01 commented
The changes requested  has been effected in the following areas;

- No more warning sign from Html Validator

- Apple logo is now a link

- All unnecessary borders removed

- The images now take 100% of its width container

- The main page elements are now links

2020-04-14 06:51 UTC, sumancrest0001 commented
**STATUS: CHANGES REQUIRED
Hello @haraphat01** 
Nice work :clap: :clap: 
Your page layout is good but we have to make sure that it looks like the original one. We have to fix a couple of issues.
[Required] Please add the stickler file. It seems you forgot to add the .stickler.yml file.

2020-04-14 06:51 UTC, sumancrest0001 commented on index.html
> +          </div>
[Require] Add links to these articles.

2020-04-14 06:53 UTC, sumancrest0001 commented on main.css
> +
[Required] width of 70% did not allow you page to cover the whole screen. Please change it.

2020-04-14 06:54 UTC, sumancrest0001 commented
[Required] Please reduce height of the vertical lines at the footer section.

2020-04-14 06:56 UTC, sumancrest0001 commented
**Kindly make the above-requested changes and submit the project for another review.
Happy coding  :slightly_smiling_face:** 
Need help feel? message me on slack **Suman Shrestha**

2020-04-14 12:10 UTC, haraphat01 commented
Thank you, TSE for the amazing job. As the necessary modifications have been applied to this.

- The width is now 100%.

- CSS linter errors have been corrected

- The vertical line section has been changed too

- Links added to the article section.

2020-04-14 12:18 UTC, mikenath223 commented
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

2020-04-14 12:53 UTC, mikenath223 requested changes
Hi @haraphat01 👋

You done quite well in this project.
Your navbar background color is really impressive👍👏

However, kindly make the below changes to make your project look even more awesome:

- [ ] Required - Kindly take a look at both screenshots below, observe the differences and make the changes that follow.
**THIS IS YOURS👇**
![ice_screenshot_20200414-132232](https://user-images.githubusercontent.com/33323077/79226049-a2fc8700-7e55-11ea-8a5b-0d8268b88fcb.png)

**THIS IS THE WAY IT SHOULD BE👇**
![ice_screenshot_20200414-133734](https://user-images.githubusercontent.com/33323077/79226113-c0c9ec00-7e55-11ea-8e3f-f4711c7b8b23.png)

Requested Changes:
* KIndly change the background-position of the main section image, as can be observed, yours is quite at the lower portion of the image, opposed to the original webpage where it is centered.

* Also increase the text sizes of the three centered text and consider placing them a bit lower on the page.

- [ ] Required - Your navbar looks quite different from the original web page. Please adjust the position of the search icon and kindly remove the white border around the search input field.
**THIS IS YOURS👇**
![ice_screenshot_20200414-132311](https://user-images.githubusercontent.com/33323077/79226914-105ce780-7e57-11ea-926f-8636ce0f91ce.png)

**THIS IS THE WAY IT SHOULD BE👇**
![ice_screenshot_20200414-135215](https://user-images.githubusercontent.com/33323077/79226992-2d91b600-7e57-11ea-8a26-1dafdf2c0da7.png)


- [ ] Required - In addition kindly increase the text size of the footer text elements, as they look quite smaller than the original webpage footer texts.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-04-14 14:12 UTC, haraphat01 commented
Thank you for the review. The following adjustment has been made;

- The position of the image has been changed.

- The font size of the paragraph  increased

- Changed on the search bar too 

- The footer has been reworked on too.

2020-04-14 23:33 UTC, christianotieno commented
## Pull Request under review by Christian Otieno (TSE)

2020-04-14 23:41 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Excellent job on this project @haraphat01. :fireworks: 
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations! :+1:
- You can now merge to master and I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-04-15 06:20 UTC, merged